
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}

stream {
	map $ssl_preread_server_name $backend_name {
        # 1.1 Your VLESS xhttp REALITY SNI
        www.varzesh3.com			127.0.0.1:10001;
        varzesh3.com				127.0.0.1:10001;
		spiegel.de					127.0.0.1:10001;
		www.partneredge.sap.com		127.0.0.1:10001;
		partneredge.sap.com			127.0.0.1:10001;
        www.yahoo.com				127.0.0.1:10002;
        yahoo.com					127.0.0.1:10002;
    

		amp-api-edge.apps.apple.com		127.0.0.1:10003;
		www.amp-api-edge.apps.apple.com	127.0.0.1:10003;

    
    # 3. Your actual website domain proxied via Cloudflare
    DOMAIN		127.0.0.1:4443;
    SUB.DOMAIN	127.0.0.1:4443;
    www.DOMAIN	127.0.0.1:4443;
        
    # 4. Fallback to the web server
    default            127.0.0.1:4443;
    }

    server {
        listen 443;
        #listen [::]:443;
        ssl_preread on;
        proxy_pass $backend_name;
    }
}

